[book]
authors = ["stigsimo"]
language = "en"
multilingual = false
src = "src"
title = "q"
[output.html]
mathjax-support = true
math = true
additional-js = ["js/custom-mathjax.js","js/eq_counter.js"]
copy-images = true